
import {Josefin_Sans, Poppins} from "next/font/google";
import "./globals.css";
import {Navbar} from "@/components/Globals/Navbar";
import {Footer} from "@/components/Globals/Footer";
import {ScrollUp} from "@/components/Globals/ScrollUp";

const josefinSans = Josefin_Sans({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-josefin-sans",
})

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700", "800", "900"],
    variable: "--font-poppins",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${josefinSans.variable} ${poppins.variable} antialiased`}>
      <Navbar/>
          {children}
      <Footer/>
      <ScrollUp/>
      </body>
    </html>
  );
}
